{% set name = "kent" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kent-{{ version }}.tar.gz
  sha256: 8a89c6fb1f4339bb5622cd26cf6411bfda636dc38798c8de6437ec1544dc173f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - kent-server=kent.cli_server:main
    - kent-testpost=kent.cli_testpost:main

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - flask >=2.1.0,<3
    - python >=3.7

test:
  source_files:
    - tests
  imports:
    - kent
  commands:
    - pip check
    - kent-server --help
    - kent-testpost --help
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest
    - sentry-sdk

about:
  home: https://github.com/willkg/kent
  summary: Fake Sentry service for debugging and integration tests
  dev_url: https://github.com/willkg/kent/
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
