{% set name = "kent" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kent-{{ version }}.tar.gz
  sha256: 36d28588372eb5aa384e785bd6072e54c5ad7ff1b8431de431e8b9ecd1c0c7a7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - kent-server=kent.cli_server:main
    - kent-testpost=kent.cli_testpost:main

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - flask >=2.1.0,<3
    - python >=3.7

test:
  source_files:
    - tests
  imports:
    - kent
  commands:
    - pip check
    - kent-server --help
    - kent-testpost --help
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest
    - requests
    - sentry-sdk

about:
  home: https://github.com/willkg/kent
  summary: Fake Sentry service for debugging and integration tests
  dev_url: https://github.com/willkg/kent/
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
