{% set name = "kent" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kent-{{ version }}.tar.gz
  sha256: 8b873ed98b8740aa6c21c5bbd83ad64d362bd3614b48bdb13d33d99bd00f4a82

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - kent-server=kent.cli_server:main
    - kent-testpost=kent.cli_testpost:main

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools
  run:
    - flask >3
    - python >=3.9
    - requests

test:
  source_files:
    - tests
  imports:
    - kent
  commands:
    - pip check
    - kent-server --help
    - kent-testpost --help
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest
    - requests
    - sentry-sdk

about:
  home: https://github.com/willkg/kent
  summary: Fake Sentry service for debugging and integration tests
  dev_url: https://github.com/willkg/kent/
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
